---
title: "Assignment 2 Jonathan Analysis 2"
output: html_document
date: "2022-09-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Part 1:
```{r}
#Dependencies
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(c("biomaRt", "DESeq2", "EDASeq", "M3C"))
if (!require("data.table")) install.packages("data.table")
library(tidyverse)
library(data.table)
library(biomaRt)
library("DESeq2")
library("EDASeq")
library("ggplot2")

#Load Necessary Data
counts_data <- fread("GSE207751_PBMC_counts.csv")
counts_data$Max <- apply(counts_data[, 3:57], MARGIN = 1, FUN = max, na.rm = TRUE)
counts_data <- counts_data[Max != 0]
counts_data <- counts_data[, !"Max", with=FALSE]
metadata <- fread("GSE207751_PBMC_metadata.csv")
mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
#Use biomaRt to convert to from Ensembl to hgnc
mapped_data <- getBM(attributes = c("ensembl_gene_id", "hgnc_symbol"), filters = "ensembl_gene_id", values = counts_data$gene_id, mart=mart)
#Remove ones without map
mapped_data <-  data.table(mapped_data[!(is.na(mapped_data$hgnc_symbol) | mapped_data$hgnc_symbol==""), ])
#combine tables
setkey(mapped_data, "ensembl_gene_id")
setkey(counts_data, "gene_id")
counts_data_filtered_hgnc <- (mapped_data[counts_data, nomatch=0])

```
```{r}
#If gene_lengths have been found, no need to refind them
if(file.exists("gene_lengths.csv")) {
  gene_lengths_table <- fread("gene_lengths.csv")
} else {
  gene_lengths <- getGeneLengthAndGCContent(counts_data_filtered_hgnc$ensembl_gene_id, org="hsa")
  gene_lengths_table <- setDT(as.data.frame(gene_lengths), keep.rownames = "ensembl_gene_id")
  fwrite(gene_lengths_table, "gene_lengths.csv")
}
counts_data_hgnc_only <- counts_data_filtered_hgnc[, !"ensembl_gene_id", with=FALSE]
counts_data_hgnc_only <- counts_data_hgnc_only[, by = hgnc_symbol, lapply(.SD, median), .SDcols = c(2:57)]
fwrite(counts_data_hgnc_only, "fixed_raw_counts.csv")
```

```{r}
#Normalize Counts
gene_lengths_table$length <- gene_lengths_table$length / 1000;
gene_lengths_table <- gene_lengths_table[, c("ensembl_gene_id", "length")]
setkey(gene_lengths_table, "ensembl_gene_id")
tpm_counts_data <- gene_lengths_table[counts_data_filtered_hgnc, nomatch=0]
tpm_counts_data <- tpm_counts_data %>% mutate(across(c(4:59), .fns= ~./length))
tpm_counts_data <- tpm_counts_data %>% mutate(across(c(4:59), .fns=~./(sum(.)/1000000)))
tpm_counts_data <- tpm_counts_data[, !c("ensembl_gene_id","length"), with=FALSE]
tpm_counts_data <- tpm_counts_data[, by = hgnc_symbol, lapply(.SD, median), .SDcols = c(2:57)]
```


```{r}
#Log specify
log_tpm_counts <- tpm_counts_data
log_tpm_counts[, 2:57] <- log_tpm_counts[, 2:57] + 1
log_tpm_counts[, 2:57] <- log(log_tpm_counts[, 2:57], 2)
log_tpm_counts$Min <- apply(log_tpm_counts[, 2:57], MARGIN=1, FUN=min, na.rm=TRUE)
log_tpm_counts$Max <- apply(log_tpm_counts[, 2:57], MARGIN=1, FUN=max, na.rm=TRUE)
log_tpm_counts$Range <- log_tpm_counts[, Max-Min]
```

```{r}
# Create density plot
density_plot_table <- log_tpm_counts[, c("hgnc_symbol", "Range")]
density_plot <- ggplot(density_plot_table, aes(x=Range)) + geom_density()
density_plot
```
Part 2:
```{r}
#PCA Plot
counts_df <- round((data.frame(counts_data_hgnc_only) %>% tibble::column_to_rownames("hgnc_symbol")), 0)
dds <- DESeqDataSetFromMatrix(countData = counts_df,
                               colData = metadata,
                               design = ~ condition)
vsd <- vst(dds, blind=FALSE)
plotPCA(vsd, intgroup="condition")
```

```{r}
#Trying TSNE
library(M3C)
vsd_data <- data(vsd)
tsne(counts_df)
```
```{r}
#Trying UMAP
umap(counts_df)
```
Part 3: 
```{r}
deseq_data <- DESeq(dds)
# had to force the correct experimental group vs control group...had no effect on our p-value but changes LFC.
deseq_data$condition <- relevel(deseq_data$condition, ref = "healthy")
deseq_data <- DESeq(deseq_data)
resultsNames(deseq_data)
deseq_results <- results(deseq_data, name='condition_ast_vs_healthy', contrast=c('condition','ast','healthy'))
head(deseq_results)
```


```{r}
deseq_results <- lfcShrink(
  deseq_data, # The original DESeq2 object after running DESeq()
  coef = 2, # The log fold change coefficient used in DESeq(); the default is 2.
  res = deseq_results # The original DESeq2 results table
)
```

```{r}
# this is of class DESeqResults -- we want a data frame
deseq_df <- deseq_results %>%
  # make into data.frame
  as.data.frame() %>%
  # the gene names are row names -- let's make them a column for easy display
  tibble::rownames_to_column("Gene") %>%
  # add a column for significance threshold results
  dplyr::mutate(threshold = padj < 0.05) %>%
  # sort by statistic -- the highest values will be genes with
  # higher expression in RPL10 mutated samples
  dplyr::arrange(dplyr::desc(log2FoldChange))
```


```{r}
head(deseq_df)
```

```{r}
# We'll assign this as `volcano_plot`
volcano_plot <- EnhancedVolcano::EnhancedVolcano(
  deseq_df,
  lab = deseq_df$Gene,
  x = "log2FoldChange",
  y = "padj",
  pCutoff = 0.01 # Loosen the cutoff since we supplied corrected p-values
)
volcano_plot

```
As the volcano plot shows, we had zero statistically significant differentially expressed genes. Therefore, we will try to continue our analysis with genes that were differentially expressed based on log-fold change.

```{r}
diffex_df <- deseq_df[deseq_df$log2FoldChange > 1,]
diffex_df <- full_join(diffex_df, deseq_df[deseq_df$log2FoldChange < -1,])
head(diffex_df)
```

Part 4:
```{r}
#FIXME
library(ComplexHeatmap)
Heatmap(diffex_df)
```
Part 5:
```{r}
#Gene Ontologies, using Biological Processes (BP), Cellular Component (CC), and REAC (pathway database)

library(gprofiler2)
gostres <- gost(diffex_df$Gene, sources = "GO:BP")
gostres2 <- gost(diffex_df$Gene, sources = "GO:CC")
gostres3 <- gost(diffex_df$Gene, sources = "REAC")
# BP Table
head(gostres$result)

# CC Table
head(gostres2$result)

# REAC Table
head(gostres3$result)

#plots of each respective GO query with highlighted terms attached for additional information
pp1 <- publish_gostplot(gostplot(gostres, capped = TRUE, interactive = FALSE), highlight_terms = gostres$result[c(1:3),])
pp2 <- publish_gostplot(gostplot(gostres2, capped = TRUE, interactive = FALSE), highlight_terms = gostres2$result[c(1:6),])
pp3 <- publish_gostplot(gostplot(gostres3, capped = TRUE, interactive = FALSE), highlight_terms = gostres3$result[c(1),])
```
