---
title: "Assignment 3"
output: html_document
date: "2022-10-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("CustomConsensusClusterPlus.R") #Added SVG Functionality to ConsensusClusterPlus
```


```{r}
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(c("data.table", "tidyverse", "svglite", "ggalluvial", "ComplexHeatmap", "circlize", "ggfortify", "magick", "GGally", "ggforce"))
library(tidyverse)
library(data.table)
library(ggfortify)
library(cluster)
library(svglite)

log_tpm_counts <- fread("fixed_logged_normalized_counts.csv")

```

```{r}
# creating redundant dataset to make changes to
plusvar_log_tpm_counts <- log_tpm_counts

# adding variance as a column so we can grab our datasets for clustering
plusvar_log_tpm_counts$var <- apply(plusvar_log_tpm_counts[, 2:57], MARGIN=1, FUN=var, na.rm=TRUE)

# ordering by highest variance first
plusvar_log_tpm_counts <- plusvar_log_tpm_counts[order(-var)]

# breaking data into smaller sets for individual clustering
ten_log_tpm_counts <- plusvar_log_tpm_counts[1:10,1:57]
hundred_log_tpm_counts <- plusvar_log_tpm_counts[1:100,1:57]
onek_log_tpm_counts <- plusvar_log_tpm_counts[1:1000,1:57]
fivek_log_tpm_counts <- plusvar_log_tpm_counts[1:5000,1:57]
tenk_log_tpm_counts <- plusvar_log_tpm_counts[1:10000,1:57]
```

```{r}
library(factoextra)
# helps figure out optimal number of clusters for PAM per:
# https://mlforanalytics.com/2020/05/23/pam-clustering-using-r/
# fviz_nbclust(fivek_log_tpm_counts[,2:57] %>% mutate(across(everything(), as.numeric)), pam, method ="silhouette")+theme_minimal()
```

```{r}
# PAM for fivek dataset
t_fiveK <- data.table::transpose(fivek_log_tpm_counts)
t_fiveK <- t_fiveK[-1] #Original included hgnc_symbol in group
t_fiveK <- as.data.frame(t_fiveK %>% mutate(across(everything(), as.numeric))) #Original turned 0s into characters which messed with pam
row.names(t_fiveK) = colnames(fivek_log_tpm_counts)[-1]
fivek_pamResults <- pam(t_fiveK, 2)
autoplot(fivek_pamResults, data = t_fiveK, frame = TRUE, frame.type = 'norm')
colnames(t_fiveK) <- fivek_log_tpm_counts$hgnc_symbol #add in genenames for posterity
#ggsave("fivek_pamresults.svg",last_plot())
```

```{r}
# PAM for ten dataset
t_ten <- data.table::transpose(ten_log_tpm_counts)
t_ten <- t_ten[-1]
t_ten <- as.data.frame(t_ten %>% mutate(across(everything(), as.numeric)))
row.names(t_ten) = colnames(ten_log_tpm_counts)[-1]
ten_pamResults <- pam(t_ten, 2) 
autoplot(ten_pamResults, frame = TRUE, frame.type = 'norm')
colnames(t_ten) <- ten_log_tpm_counts$hgnc_symbol
#ggsave("ten_pamresults.svg",last_plot())
```

```{r}
# PAM for hundred dataset
t_hundred <- data.table::transpose(hundred_log_tpm_counts)
t_hundred <- t_hundred[-1]
t_hundred <- as.data.frame(t_hundred %>% mutate(across(everything(), as.numeric)))
row.names(t_hundred) = colnames(hundred_log_tpm_counts)[-1]
hundred_pamResults <- pam(t_hundred, 2)
autoplot(hundred_pamResults, frame = TRUE, frame.type = 'norm')
colnames(t_hundred) <- hundred_log_tpm_counts$hgnc_symbol
#ggsave("hundred_pamresults.svg",last_plot())
```
```{r}
# PAM for onek dataset
t_onek <- data.table::transpose(onek_log_tpm_counts)
t_onek <- t_onek[-1]
t_onek <- as.data.frame(t_onek %>% mutate(across(everything(), as.numeric)))
row.names(t_onek) = colnames(onek_log_tpm_counts)[-1]
onek_pamResults <- pam(t_onek, 2)
autoplot(onek_pamResults, frame = TRUE, frame.type = 'norm')
colnames(t_onek) <- onek_log_tpm_counts$hgnc_symbol
#ggsave("onek_pamresults.svg",last_plot())
```

```{r}
# PAM for tenk dataset
t_tenk <- data.table::transpose(tenk_log_tpm_counts)
t_tenk <- t_tenk[-1]
t_tenk <- as.data.frame(t_tenk %>% mutate(across(everything(), as.numeric)))
row.names(t_tenk) = colnames(tenk_log_tpm_counts)[-1]
tenk_pamResults <- pam(t_ten, 2)
autoplot(tenk_pamResults, frame = TRUE, frame.type = 'norm')
colnames(t_tenk) <- tenk_log_tpm_counts$hgnc_symbol
#ggsave("tenk_pamresults.svg",last_plot())
```

```{r}
# PAM Sankey Diagram
library(ggalluvial)
metadata <- fread("GSE207751_PBMC_metadata.csv")
tenClust <- data.table(ten_pamResults$clustering)
hunClust <- data.table(hundred_pamResults$clustering)
onekClust <- data.table(onek_pamResults$clustering)
fivekClust <- data.table(fivek_pamResults$clustering)
tenkClust <- data.table(tenk_pamResults$clustering)
clustInfo <- data.table(colnames(fivek_log_tpm_counts))[-1]
colnames(clustInfo)[1] = "samples"
clustInfo$`10` <- tenClust
clustInfo$`100` <- hunClust
clustInfo$`1000` <- onekClust
clustInfo$`5000` <- fivekClust
clustInfo$`10000` <- tenkClust
clustInfo$Condition <- metadata[,6]
# PAM Sankey
ggplot(clustInfo,
     aes(axis2 = `10`, axis3 = `100`, axis4 = `1000`, axis5= `5000`, axis6 = `10000`)) +
  geom_alluvium(aes(fill = Condition), color = "black", width = 1/2, show.legend = TRUE) +
  geom_stratum(width = 1/2, fill = "blue", color = "grey") +
  geom_stratum(width = 1/2, fill = "lightgray", color = "black") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("10", "100", "1000", "5000", "10000"), expand = c(.05, .05)) +
  ggtitle("PAM Sample Clustering Based on Number of Genes") + ylab("Sample Frequency") + xlab("Amount of Genes")
ggsave("Alluvial_PAM.svg")
```

```{r}
#KMeans Clustering with 5,000 genes
#preforming kmeans with 5 thousand genes
#remove first column as kmeans can not take non-numeric values #EDITED OUT NON NEEDED WORK
#apply kmeans clustering algorithim for kvalues 1-4 and plot

fivek_kmeans_1 <- kmeans(t_fiveK, 1, nstart = 25)
autoplot(fivek_kmeans_1, data=t_fiveK, frames = TRUE, frame.type = 'norm')
#ggsave("fivek_kmeansresults_k_1.svg",last_plot())

fivek_kmeans_2 <- kmeans(t_fiveK, 2, nstart = 25)
autoplot(fivek_kmeans_2, t_fiveK , frames = TRUE, frame.type = 'norm')
#ggsave("fivek_kmeansresults_k_2.svg",last_plot())

fivek_kmeans_3 <- kmeans(t_fiveK, 3, nstart = 25)
autoplot(fivek_kmeans_3, t_fiveK , frames = TRUE, frame.type = 'norm')
#ggsave("fivek_kmeansresults_k_3.svg",last_plot())

fivek_kmeans_4 <- kmeans(t_fiveK, 4, nstart = 25)
autoplot(fivek_kmeans_4, t_fiveK , frames = TRUE, frame.type = 'norm')
#ggsave("fivek_kmeansresults_k_4.svg",last_plot())
```

```{r}
#apply kmeans clustering algorithim for kvalues 1-4 and plot

ten_kmeans_1 <- kmeans(t_ten, 1, nstart = 25)
autoplot(ten_kmeans_1, t_ten , frames = TRUE, frame.type = 'norm')
#ggsave("ten_kmeansresults_k_1.svg",last_plot())

ten_kmeans_2 <- kmeans(t_ten, 2, nstart = 25)
autoplot(ten_kmeans_2, t_ten , frames = TRUE, frame.type = 'norm')
#ggsave("ten_kmeansresults_k_2.svg",last_plot())

ten_kmeans_3 <- kmeans(t_ten, 3, nstart = 25)
autoplot(ten_kmeans_3, t_ten , frames = TRUE, frame.type = 'norm')
#ggsave("ten_kmeansresults_k_3.svg",last_plot())

ten_kmeans_4 <- kmeans(t_ten, 4, nstart = 25)
autoplot(ten_kmeans_4, t_ten , frames = TRUE, frame.type = 'norm')
#ggsave("ten_kmeansresults_k_4.svg",last_plot())
```

```{r}
#KMeans Clustering with 100 genes

#remove column with gene names #EDITED TO USE PREVIOUS WORK
# hundred_counts_ns <- hundred_log_tpm_counts[,-1]

#transpose data to cluster by sample
# t_hundred <- transpose(hundred_counts_ns)

#apply kmeans clustering algorithim for kvalues 1-4 and plot

hundred_kmeans_1 <- kmeans(t_hundred, 1, nstart = 25)
autoplot(hundred_kmeans_1, t_hundred , frames = TRUE, frame.type = 'norm')
#ggsave("hundred_kmeansresults_k_1.svg",last_plot())

hundred_kmeans_2 <- kmeans(t_hundred, 2, nstart = 25)
autoplot(hundred_kmeans_2, t_hundred , frames = TRUE, frame.type = 'norm')
#ggsave("hundred_kmeansresults_k_2.svg",last_plot())

hundred_kmeans_3 <- kmeans(t_hundred, 3, nstart = 25)
autoplot(hundred_kmeans_3, t_hundred , frames = TRUE, frame.type = 'norm')
#ggsave("hundred_kmeansresults_k_3.svg",last_plot())

hundred_kmeans_4 <- kmeans(t_hundred, 4, nstart = 25)
autoplot(hundred_kmeans_4, t_hundred , frames = TRUE, frame.type = 'norm')
#ggsave("hundred_kmeansresults_k_4.svg",last_plot())
```

```{r}
#KMeans Clustering with 1,000 genes

#remove column with gene names
#onek_counts_ns <- onek_log_tpm_counts[,-1]

#transpose data to cluster by sample
#t_onek_counts <- transpose(onek_counts_ns)

#apply kmeans clustering algorithim for kvalues 1-4 and plot

onek_kmeans_1 <- kmeans(t_onek, 1, nstart = 25)
autoplot(onek_kmeans_1, t_onek , frames = TRUE, frame.type = 'norm')
#ggsave("onek_kmeansresults_k_1.svg",last_plot())

onek_kmeans_2 <- kmeans(t_onek, 2, nstart = 25)
autoplot(onek_kmeans_2, t_onek , frames = TRUE, frame.type = 'norm')
#ggsave("onek_kmeansresults_k_2.svg",last_plot())

onek_kmeans_3 <- kmeans(t_onek, 3, nstart = 25)
autoplot(onek_kmeans_3, t_onek , frames = TRUE, frame.type = 'norm')
#ggsave("onek_kmeansresults_k_3.svg",last_plot())

onek_kmeans_4 <- kmeans(t_onek, 4, nstart = 25)
autoplot(onek_kmeans_4, t_onek , frames = TRUE, frame.type = 'norm')
#ggsave("onek_kmeansresults_k_4.svg",last_plot())
```

```{r}
#KMeans Clustering with 10,000 genes

#remove column with gene names
#tenk_counts_ns <- tenk_log_tpm_counts[,-1]

#transpose data to cluster by sample
#t_tenk_counts <- transpose(tenk_counts_ns)

#apply kmeans clustering algorithim for kvalues 1-4 and plot

tenk_kmeans_1 <- kmeans(t_tenk, 1, nstart = 25)
autoplot(tenk_kmeans_1, t_tenk , frames = TRUE, frame.type = 'norm')
#ggsave("tenk_kmeansresults_k_1.svg",last_plot())

tenk_kmeans_2 <- kmeans(t_tenk, 2, nstart = 25)
autoplot(tenk_kmeans_2, t_tenk , frames = TRUE, frame.type = 'norm')
#ggsave("tenk_kmeansresults_k_2.svg",last_plot())

tenk_kmeans_3 <- kmeans(t_tenk, 3, nstart = 25)
autoplot(tenk_kmeans_3, t_tenk , frames = TRUE, frame.type = 'norm')
#ggsave("tenk_kmeansresults_k_3.svg",last_plot())

tenk_kmeans_4 <- kmeans(t_tenk, 4, nstart = 25)
autoplot(tenk_kmeans_4, t_tenk , frames = TRUE, frame.type = 'norm')
#ggsave("tenk_kmeansresults_k_4.svg",last_plot())
```

```{r}
# KMeans Sankey Diagram of K = 2 Data

#Combine K = 2 data into one table
kclustInfo <- data.table(colnames(fivek_log_tpm_counts))
kclustInfo <- kclustInfo[-1,]
ktenClust <- data.table(ten_kmeans_2$cluster)
khundredClust <- data.table(hundred_kmeans_2$cluster)
konekClust <- data.table(onek_kmeans_2$cluster)
kfivekClust <- data.table(fivek_kmeans_2$cluster)
ktenkClust <- data.table(tenk_kmeans_2$cluster)
colnames(kclustInfo)[1] = "samples"
kclustInfo$`10` <- ktenClust
kclustInfo$`100` <- khundredClust
kclustInfo$`1000` <- konekClust
kclustInfo$`5000` <- kfivekClust
kclustInfo$`10000` <- ktenkClust
kclustInfo$Condition <- metadata[,6]

# Create Sankey Plot of K = 2 Data
ggplot(kclustInfo,
     aes(axis2 = `10`, axis3 = `100`, axis4 = `1000`, axis5= `5000`, axis6 = `10000`)) +
  geom_alluvium(aes(fill = Condition), width = 1/2, show.legend = TRUE) +
  geom_stratum(width = 1/2, fill = "blue", color = "grey") +
  geom_stratum(width = 1/2, fill = "lightgray", color = "black") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("10", "100", "1000", "5000", "10000"), expand = c(.05, .05)) +
  ggtitle("KMeans Sample Clustering Based on Number of Genes") + ylab("Sample Frequency") + xlab("Amount of Genes")
ggsave("Alluvial_KMeans.svg")
```

```{r}
seed_val <- runif(1, min = 0.01 , max = 2^31) # For completeness all runs with different gene amounts will use the same seed_val
```

```{r}
top_10_counts_data <- as.data.frame(ten_log_tpm_counts) %>% tibble::column_to_rownames("hgnc_symbol") %>% as.matrix 
results_10 <- ConsensusClusterPlus(top_10_counts_data, maxK=20, reps=1000, pItem=0.8, pFeature = 1, title="Top 10 Genes", clusterAlg = "hc", distance = "pearson", seed = seed_val, plot = NULL) #replace with plot = "svg" for save
```
```{r}
top_100_counts_data <- as.data.frame(hundred_log_tpm_counts) %>% tibble::column_to_rownames("hgnc_symbol") %>% as.matrix 
results_100 <- ConsensusClusterPlus(top_100_counts_data, maxK=20, reps=1000, pItem=0.8, pFeature = 1, title="Top 100 Genes", clusterAlg = "hc", distance = "pearson", seed = seed_val, plot = NULL) #replace with plot = "svg" for save
```
```{r}
top_1000_counts_data <- as.data.frame(onek_log_tpm_counts) %>% tibble::column_to_rownames("hgnc_symbol") %>% as.matrix 
results_1000 <- ConsensusClusterPlus(top_1000_counts_data, maxK=20, reps=1000, pItem=0.8, pFeature = 1, title="Top 1000 Genes", clusterAlg = "hc", distance = "pearson", seed = seed_val, plot = NULL) #replace with plot = "svg" for save
```
```{r}
top_5000_counts_data <- as.data.frame(fivek_log_tpm_counts) %>% tibble::column_to_rownames("hgnc_symbol") %>% as.matrix 
results_5000 <- ConsensusClusterPlus(top_5000_counts_data, maxK=20, reps=1000, pItem=0.8, pFeature = 1, title="Top 1000 Genes", clusterAlg = "hc", distance = "pearson", seed = seed_val, plot = NULL) #replace with plot = "svg" for save
```
```{r}
top_10000_counts_data <- as.data.frame(tenk_log_tpm_counts) %>% tibble::column_to_rownames("hgnc_symbol") %>% as.matrix 
results_10000 <- ConsensusClusterPlus(top_10000_counts_data, maxK=20, reps=1000, pItem=0.8, pFeature = 1, title="Top 10000 Genes", clusterAlg = "hc", distance = "pearson", seed = seed_val, plot = NULL) #replace with plot = "svg" for save
```
```{r}
alluvial_data <- setNames(inner_join(inner_join(inner_join(inner_join(rownames_to_column(as.data.frame(results_10[[10]]$consensusClass)), 
                                                             rownames_to_column(as.data.frame(results_100[[10]]$consensusClass))), 
                                                  rownames_to_column(as.data.frame(results_1000[[10]]$consensusClass))), 
                                       rownames_to_column(as.data.frame(results_5000[[10]]$consensusClass))), 
                            rownames_to_column(as.data.frame(results_10000[[10]]$consensusClass))), 
                          c("Samples", "10", "100", "1000", "5000", "10000")) %>% column_to_rownames("Samples")
alluvial_data$unique <- paste(as.character(alluvial_data$`10`), as.character(alluvial_data$`100`), as.character(alluvial_data$`1000`), as.character(alluvial_data$`5000`), as.character(alluvial_data$`10000`))
freqs <- table(alluvial_data$unique)
alluvial_data <- distinct(alluvial_data)
alluvial_data$`Sample Frequency` <- freqs[alluvial_data$unique]
alluvial_data <- subset(alluvial_data, select = -unique)
rownames(alluvial_data) <- NULL
lodes_data <- to_lodes_form(alluvial_data, axes= 1:5, key = "Amount of Genes Used", value = "Cluster")
ggplot(lodes_data, aes(y = `Sample Frequency`, x = `Amount of Genes Used`, stratum = `Cluster`, alluvium = alluvium, fill = `Cluster`, label = `Cluster`)) + scale_fill_brewer(type = "qual", palette = "Set3") + geom_flow(stat = "alluvium", lode.guidance = "frontback", color = "darkgrey") + geom_stratum() +  scale_y_continuous(name = "Sample Frequency", limits =c(0, 57)) + ggtitle("ConsensusClusterPlus Sample Clustering Based on Number of Genes")
ggsave("Alluvial_CCP.svg")
```
```{r}
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
top_5000_matrix <- t(as.matrix(top_5000_counts_data))
colnames(top_5000_matrix) <- NULL
cols_10 <- brewer.pal(10, "Paired")
cols_condition <- brewer.pal(3, "Set1")[1:2]
cols_2 <- brewer.pal(3, "Set2")[1:2]
names(cols_condition) <- c("healthy", "ast")
names(cols_10) <- as.character(1:10)
names(cols_2) <- as.character(1:2)
ha <- rowAnnotation(Condition = as.data.frame(metadata) %>% select(c("Patient_id","condition")) %>% tibble::deframe(), PAM = as.character(fivek_pamResults$clustering), KMeans = as.character(kclustInfo %>% select(c("samples", "5000")) %>% tibble::deframe()),  CCP = as.character(results_5000[[10]]$consensusClass), col = list(Condition = cols_condition, PAM = cols_2, KMeans = cols_2, CCP = cols_10), show_legend = c(KMeans = FALSE), annotation_legend_param = list(PAM = list(title = "k = 2"), CCP = list(title = "k = 10", labels = as.character(1:10))))
ht <- Heatmap(top_5000_matrix, name="Expression", column_title = "Top 5000 Genes by Variance", column_title_side = "bottom", right_annotation = ha)
draw(ht)
 svg("heatmap.svg", width = 32, height = 20)
 draw(ht, use_raster = FALSE)
 dev.off()
 png("heatmap.png", width = 2560, height = 1600)
 draw(ht)
 dev.off
```


```{r} 
library(GGally) # I think this section is the wrong idea!!!!!
# Chi Square for PAM compared to Metadata
metaCondensed <- metadata[,-c(2:5)]
#metaCondensed$condition[metaCondensed$condition=="ast"] <- 1 
#metaCondensed$condition[metaCondensed$condition=="healthy"] <- 2
chiSqData <- metaCondensed
chiSqData$PAM = clustInfo[,5]
summaryConditionPAM <- chisq.test(table(chiSqData$condition,chiSqData$PAM))
#p.adjust(summaryConditionPAM$p.value, n=6) # dependent (p low reject Ho) n = 3 as there are 6 different hypotheses (condition v PAM, condition v KMeans, condition v CCP, PAM v KMeans, PAM v CCP, KMeans v CCP)
statTestResults <- list()
statTestResults$ConditionPAM = c("p-value"=summaryConditionPAM$p.value)
# Chi Square for K-Means compared to Metadata
chiSqData$KMeans = kclustInfo[,4]
summaryConditionKMeans <- chisq.test(table(chiSqData$condition,chiSqData$KMeans))
#p.adjust(summaryKMeans$p.value, n=2) # dependent (p low reject Ho)
statTestResults$ConditionKMeans = c("p-value"=summaryConditionKMeans$p.value)
chiSqData$CCP <- results_5000[[10]]$consensusClass
summaryConditionCCP <- chisq.test(table(chiSqData$condition, chiSqData$CCP))
statTestResults$ConditionCCP <- c("p-value"=summaryConditionCCP$p.value)
summaryPAMKMeans <- chisq.test(table(chiSqData$PAM, chiSqData$KMeans))
statTestResults$PAMKMeans <- c("p-value"=summaryPAMKMeans$p.value)
summaryPAMCCP <- chisq.test(table(chiSqData$PAM, chiSqData$CCP))
statTestResults$PAMCCP <- c("p-value"=summaryPAMCCP$p.value)
summaryKMeansCCP <- chisq.test(table(chiSqData$KMeans, chiSqData$CCP))
statTestResults$KMeansCCP <- c("p-value"=summaryKMeansCCP$p.value)
statTestResults <- mutate(as.data.frame(statTestResults), across(everything(), as.numeric))
statTestResults <- as.data.frame(rbind(statTestResults, p.adjust(as.vector(statTestResults))))
row.names(statTestResults) <- c("p-value", "p-adj")
statTestResults
chiSqData <- chiSqData %>% mutate(across(c(3:5), as.character))
chiSqData$CCP <- paste0("\U00A0", chiSqData$CCP) #Put columns in correct order
chiSqData$CCP[chiSqData$CCP == paste0("\U00A0","10")] <- "10" #Not super efficient, but works
pm <- ggpairs(chiSqData, mapping = aes(color = condition), title = "Comparison of PAM, KMeans, CCP and experimental clustering", columns = 2:5, lower = list(
  discrete = "autopoint"
), diag = list(
  discrete = "densityDiag"
), upper = list(
  discrete = "facetbar"
))
pm
# ggsave("enrichment_plot.svg", width=10, height=10)

```
