---
title: Assignment 3 Kmeans Clustering
date: 10/21/2022
---

```{r}
library(tidyverse)
library(data.table)
library(ggfortify)
library(cluster)
library(factoextra)

log_tpm_counts <- fread("fixed_logged_normalized_counts.csv")

```


```{r}
# creating redundant dataset to make changes to
plusvar_log_tpm_counts <- log_tpm_counts

# adding variance as a column so we can grab our datasets for clustering
plusvar_log_tpm_counts$var <- apply(plusvar_log_tpm_counts[, 2:57], MARGIN=1, FUN=var, na.rm=TRUE)

# ordering by highest variance first
plusvar_log_tpm_counts <- plusvar_log_tpm_counts[order(-var)]

# breaking data into smaller sets for individual clustering
ten_log_tpm_counts <- plusvar_log_tpm_counts[1:10,1:57]
hundred_log_tpm_counts <- plusvar_log_tpm_counts[1:100,1:57]
onek_log_tpm_counts <- plusvar_log_tpm_counts[1:1000,1:57]
fivek_log_tpm_counts <- plusvar_log_tpm_counts[1:5000,1:57]
tenk_log_tpm_counts <- plusvar_log_tpm_counts[1:10000,1:57]
```

```{r}
#set seed value for less variation in kmeans results
set.seed(237)
```


```{r}
#preforming kmeans with 5 thousand genes

#remove first column as kmeans can not take non-numeric values
fivek_log_tpm_counts_ns <- fivek_log_tpm_counts[,-1]

#preform kmeans with k = 1 and plot results
k4.res <- kmeans(fivek_log_tpm_counts_ns, 1, nstart = 25)
autoplot(k4.res, fivek_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 2 and plot results
k4.res <- kmeans(fivek_log_tpm_counts_ns, 2, nstart = 25)
autoplot(k4.res, fivek_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 3 and plot results
k4.res <- kmeans(fivek_log_tpm_counts_ns, 3, nstart = 25)
autoplot(k4.res, fivek_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 4 and plot results
k4.res <- kmeans(fivek_log_tpm_counts_ns, 4, nstart = 25)
autoplot(k4.res, fivek_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')
```


```{r}
#preforming kmeans with 10 genes

#remove first column as kmeans can not take non-numeric values
ten_log_tpm_counts_ns <- ten_log_tpm_counts[,-1]

#preform kmeans with k = 1 and plot results
k4.res <- kmeans(ten_log_tpm_counts_ns, 1, nstart = 25)
autoplot(k4.res, ten_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 2 and plot results
k4.res <- kmeans(ten_log_tpm_counts_ns, 2, nstart = 25)
autoplot(k4.res, ten_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 3 and plot results
k4.res <- kmeans(ten_log_tpm_counts_ns, 3, nstart = 25)
autoplot(k4.res, ten_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 4 and plot results
k4.res <- kmeans(ten_log_tpm_counts_ns, 4, nstart = 25)
autoplot(k4.res, ten_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')
```

```{r}
#preforming kmeans with 100 genes

#remove first column as kmeans can not take non-numeric values
hundred_log_tpm_counts_ns <- hundred_log_tpm_counts[,-1]

#preform kmeans with k = 1 and plot results
k4.res <- kmeans(hundred_log_tpm_counts_ns, 1, nstart = 25)
autoplot(k4.res, hundred_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 2 and plot results
k4.res <- kmeans(hundred_log_tpm_counts_ns, 2, nstart = 25)
autoplot(k4.res, hundred_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 3 and plot results
k4.res <- kmeans(hundred_log_tpm_counts_ns, 3, nstart = 25)
autoplot(k4.res, hundred_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 4 and plot results
k4.res <- kmeans(hundred_log_tpm_counts_ns, 4, nstart = 25)
autoplot(k4.res, hundred_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')
```


```{r}
#preforming kmeans with 1 thousand genes

#remove first column as kmeans can not take non-numeric values
onek_log_tpm_counts_ns <- onek_log_tpm_counts[,-1]

#preform kmeans with k = 1 and plot results
k4.res <- kmeans(onek_log_tpm_counts_ns, 1, nstart = 25)
autoplot(k4.res, onek_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 2 and plot results
k4.res <- kmeans(onek_log_tpm_counts_ns, 2, nstart = 25)
autoplot(k4.res, onek_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 3 and plot results
k4.res <- kmeans(onek_log_tpm_counts_ns, 3, nstart = 25)
autoplot(k4.res, onek_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 4 and plot results
k4.res <- kmeans(onek_log_tpm_counts_ns, 4, nstart = 25)
autoplot(k4.res, onek_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')
```

```{r}
#preforming kmeans with 10,000 genes

#remove first column as kmeans can not take non-numeric values
tenk_log_tpm_counts_ns <- tenk_log_tpm_counts[,-1]

#preform kmeans with k = 1 and plot results
k4.res <- kmeans(tenk_log_tpm_counts_ns, 1, nstart = 25)
autoplot(k4.res, tenk_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 2 and plot results
k4.res <- kmeans(tenk_log_tpm_counts_ns, 2, nstart = 25)
autoplot(k4.res, tenk_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 3 and plot results
k4.res <- kmeans(tenk_log_tpm_counts_ns, 3, nstart = 25)
autoplot(k4.res, tenk_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')

#preform kmeans with k = 4 and plot results
k4.res <- kmeans(tenk_log_tpm_counts_ns, 4, nstart = 25)
autoplot(k4.res, tenk_log_tpm_counts[,-1], frame = TRUE, frame.type = 'norm')
```


